### ISSUE TITLE
MongoBrowser (force re-) opens Mongo default and flushes the authentication cache

### ISSUE THREAD

**Issue by krodelin** [pharo-nosql/mongotalk#13]
Opening `MongoBrowser` from the world menu or directly via `MongoBrowser open` flushes the authentication cache.

```
Mongo default authenticateUsername: 'admin' password: 'password'  database: (Mongo default databaseNamed: 'admin').
MongoBrowser openOn: Mongo default. "This works"
MongoBrowser open. "This doesn't. MongoBrowser>>#open sends #open to Mongo default which clears the auth cache :-("
```

This is due to the implementation in `MongoBrowser>>#open` which (re-)opens the connection:

```
open
	<script>

	self openOn: Mongo default open 
```

And `Mongo>>#open` flushes `authCache`:

```
open
	stream := GratuitousIncompatibilities socketStreamHost: host port: port.
	authCache := nil
```

A possible fix for `MongoBrowser>>#open' might be:

```
open
	<script>
	| mongo |
	mongo := Mongo default.
	mongo isOpen isFalse: [ mongo open ].
	self openOn: mongo
```

**Comment by SabineMa** [comment]
If we succeeded in opening the MongoBrowser, the different databases are protected themselves, too. And they have other users ans passwords. For this reason, the collections command should be extended e.g. like this:


```
	[ self command: {(#listCollections -> 1)} asDictionary ]
		on: MongoCommandError
		do: [ :error | 
			(error reply at: 'code') = 13
				ifTrue: [ root
						authenticateUsername:
							(UIManager default
								request: ('Please enter username for database {1}' format: {self name})
								initialAnswer: ''
								title: 'Database is protected')
						password: (UIManager default request: ('password for database {1}' format: {self name}) initialAnswer: '' title: 'Database is protected')
						database: self ] ].
	reply := self command: {(#listCollections -> 1)} asDictionary.
	names := ((reply at: 'cursor') at: 'firstBatch') collect: [ :each | each at: #name ].
	"real := names select: [:each | (each occurrencesOf: $.) = 1].
    stripped := real collect: [:each | each readStream upTo: $.; upToEnd]."
	^ names collect: [ :each | MongoCollection database: self name: each ]
```

**Comment by krodelin** [comment]
I'm not quite sure if it's a good idea to call UI functions here. Just think of this code running in a headless image. IMHO you can pre-configure multiple credentials:
```
mongo := (Mongo host: 'localhost' port: 27017)
	open;
	yourself.
mongo 	authenticateUsername: 'admin' password: 'password1'  database: (mongo databaseNamed: 'db1');
	authenticateUsername: 'admin' password: 'password2'  database: (mongo databaseNamed: 'db2').
MongoBrowser openOn: mongo.
```

**Comment by estebanlm** [comment]
no direct access to UI, please :)
correct behaviour is to throw an error and let users handle it (with a retry or whatever)

**Comment by SabineMa** [comment]
yes it would be better to move the UIManager call to the MongoBrower instead of the collection method.

**Comment by noha** [comment]
I don't understand the problem. MongoBrowser open opens a browser on a new connection. ```Mongo default``` does not say default connection but rather default configuration. Authentication information in mongo is per connection so it has to be flushed on new connection. Mongo browser has also #openOn: which can be used to reuse and exsiting mongo.
I'm closing this because I don't see the problem. Reopen if there is still a problem and make a PR with a solution. Thanks
