### ISSUE TITLE
queryOne: does now return self instead of nil if nothing is found

### ISSUE THREAD

**Issue by noha** [pharo-nosql/mongotalk#14]
What was the rationale for the change?

**Comment by tinchodias** [comment]
Woo... too much time passed. Sorry! don't know why I didn't answer you. I agree the change doesn't make sense. It was proposed in issue #10 and the wrong rationale **might** be this: I supposed when no result is found, anyway the doBlock was evaluated with $err in the reply.

```
queryOne: aMongoQuery
	aMongoQuery doBlock: [:each | 
		^(each includesKey: '$err')
			ifTrue: [ MongoQueryError signalFor: each ]
			ifFalse: [ each ] ].
	aMongoQuery chunkSize: 1.
	(MongoCursor new
		root: self;
		query: aMongoQuery;
		execute).
	^nil
```
