### ISSUE TITLE
Release 1.11.3

### ISSUE THREAD

**Issue by tinchodias** [pharo-nosql/mongotalk#24]
After merging PR #23, I'd like to release 1.11.3. It only adds BSON support to OrderedDictionary.

**Comment by estebanlm** [comment]
go ahead :)

**Comment by tinchodias** [comment]
I created 1.11.3 via github, that was good. After I tried to move 1.11 to point to the same commit but I couldn't. Should I skip web ui and use "git tag --force" to move the existing tag?

**Comment by estebanlm** [comment]
yep ;)

**Comment by tinchodias** [comment]
done, thkns
