### ISSUE TITLE
Fix #mongo3CollectionNames to list beyond firstBatch

### ISSUE THREAD

**Issue by tinchodias** [pharo-nosql/mongotalk#29]
Bug introduced with #27 workaround

**Comment by noha** [comment]
What is the status of this?

**Comment by tinchodias** [comment]
It isn't fixed (just checked). 

OT: I read in [a voyage's issue](https://github.com/pharo-nosql/voyage/pull/123) about dropping support for mongodb<3.4. If we do it also in this driver, we could simplify this implementation too... e.g.:

~~~
collections
	"Answer the collections in this database"

	| collectionNames |
	collectionNames := root majorVersion < 3
		ifTrue: [ self mongo2CollectionNames ]
		ifFalse: [ self mongo3CollectionNames ].
	^ collectionNames
		collect: [:each | MongoCollection database: self name: each ]
~~~

**Comment by noha** [comment]
We dropped support for mongo <3.4 so you can remove that code.

**Comment by tinchodias** [comment]
I created #48.

**Comment by noha** [comment]
To be honest I try to get rid of issues. Why did you create a new one?

**Comment by tinchodias** [comment]
#48 was clean up issue, this is a bug. I created this issue as a "todo", to recall that if somebody has a database with many collections will get only a part of them as answer to #collections.
