### ISSUE TITLE
Remove MongoMetaCollection?

### ISSUE THREAD

**Issue by tinchodias** [pharo-nosql/mongotalk#33]
A MongoMetaCollection is a subclass of MongoCollection that adds an instance creation method that allows to do not specify a database, as it's superclass.

It has 2 uses in the project:

MongoMetaCollection name: '$cmd'
MongoMetaCollection name: 'system.namespaces'

My problem with this class is that AFAIK there aren't "meta collections" in mongodb. IMO mongotalk as a mongodb driver is good/useful/effective when you can mentally map a mongotalk concept to a mongodb concept. I mean, if you see a class in the code then you can find it in mongodb doc and viceversa. The 2 uses above mentioned are not the case... they can be easily replaced by MongoCollection. 

Concretely, I tried: 
```
MongoMetaCollection name: '$cmd' 
```
changed to:
```
MongoCollection database: aDatabase name: '$cmd'
```
and also with 'system.namespaces', and it worked (after fixing a couple of lines but look good). Maybe I should had directly created a PR and discuss there... probably soon.

**Comment by noha** [comment]
Is this still an issue? Can you provide a PR?

**Comment by tinchodias** [comment]
Thanks for reviewing these stale issues. I should create a PR in few days... or close this issue.

**Comment by noha** [comment]
ping
