### ISSUE TITLE
[feature request] Ability to send queries in raw js syntax

### ISSUE THREAD

**Issue by sebastianconcept** [pharo-nosql/mongotalk#40]
Hi there, and thanks for MongoTalk! it's  agreat piece of software and convenient way to access MongoDB from Pharo. I'd like to have a feature that I think is currently missing and it would be extremely useful and powerful IMHO: being able to send a query in raw JavaScript syntax and yet receive the answer as we would expect in any other MongoTalk query.

Here is why:

In real applications you often have aggregations and queries that use advanced MongoDB features. Those queries are complex enough in their native syntax and adding a layer of complexity in translating it to "the MongoTalk way" makes them orders of magnitude more complex and verbose. And that's when even possible from Smalltalk because is easy to get to the point of a missing MongoDB feature in MongoTalk as client.

The need for those queries is not going to go away because you want to be able to take advantage of the DB engine advanced features and also demands that are simply out of your control. 

So, as I see it, there are two paths to take:

1. Extend _the MongoTalk's way_ with the missing feature.
2. Add to MongoTalk the ability to send queries in raw JavaScript.

As good as 1 is, it still have the problem of having to "translate" original queries that were designed in JavaScript into the _the MongoTalk way_ which consumes time for no good reason and it takes a significant effort in time to get those features nailed one by one without introducing bugs. All this is  delaying the point in which you can start delivering more value from MongoTalk.

I propose to **add to MongoTalk the ability to send queries in raw JavaScript** because, while it doesn't exclude you from eventually implementing _the MongoTalk way_ to do queries, it provides of the full power of MongoDB for those who know what they are doing.

It wouldn't be rare that a database in MongoDB is shared among other services with their own history. History that some times will have database design that wasn't the most brilliant structure the app could have and yet you can come in with Pharo and create a microservice that yields on that data and process it providing a very valuable service that other parts can't. Actually that would be a great case. It would be Pharo winning new territory over other software that is just too messy to be extended.

**Comment by tinchodias** [comment]
Hi. I agree to provide 2. first but without discarding 1 if possible.

**Comment by sebastianconcept** [comment]
Just a random thought... if for doing this, we can have a way to send _any_ raw js command to the mongo client, that would be huge. Mongo is adding plenty of these that we wouldn't have to maintain if we can just proxy to their client.
[
![hey-client_ _mongo_ _mongo_ _mongo_ _158x35](https://user-images.githubusercontent.com/475508/49544697-a4618b00-f8c2-11e8-881d-f1b4f645049b.png)
](url)

**Comment by Ducasse** [comment]
You see Esteban has only 24h a day. Now you can also contribute, even to other subsystems, why?
Because when people help elsewhere we have more time for the rest. 
It looks simple but this is true.

**Comment by noha** [comment]
This issue is more than 3 months old and no PR has been submitted. So I consider that issue as not needed and will close any time soon

**Comment by tinchodias** [comment]
@sebastianconcept did you try to implement this feature?

By raw js syntax, you were speaking of this stuff, right?
~~~
db.inventory.find( {
     status: "A",
     $or: [ { qty: { $lt: 30 } }, { item: /^p/ } ]
} )
~~~
(extracted from [here](https://docs.mongodb.com/manual/tutorial/query-documents/))

I can be wrong, but I think you could base on the `QueryOperation` class but have a #computeDataBytes that is less smart and just answers something like `^ BSON writeAll: rawQuery`.

AFAIU, the mentioned class implements [this spec](https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/#op-query).

**Comment by noha** [comment]
Seems to be no interested in this. Closing
