### ISSUE TITLE
system.namespaces deprecated in MongoDB 3.0 breaks MongoDatabase>>collections

### ISSUE THREAD

**Issue by sebastianconcept** [pharo-nosql/mongotalk#42]
As per [this MongoDB doc](https://docs.mongodb.com/manual/reference/system-collections/#%3Cdatabase%3E.system.namespacesl), `system.namespaces` is deprecated since version `3.0`.

MongoTalk is using it for the current implementation of `MongoDatabase>>collections`.

It won't work when connected to a `MongoDB 4.x.x`

I've patched it with:

```
MongoDatabase>>collections
	| stripped |
	stripped := (self command: {(#listCollections -> 1)} asDictionary) cursor firstBatch
		collect: [ :e | e name ].
	^ stripped collect: [ :each | MongoCollection database: self name: each ]

```

**Comment by estebanlm** [comment]
can you send a PR? thanks!

**Comment by sebastianconcept** [comment]
@estebanlm I didn't send PR because in the last version this is properly implemented already so I think we can close this issue

**Comment by estebanlm** [comment]
oks
