### ISSUE TITLE
P9 - GRCodec missing

### ISSUE THREAD

**Issue by amiracam** [pharo-nosql/mongotalk#79]
any attempt to engage Mongo generates this error

e.g.
Open MongoBrowser

error:

GRUnsupportedEncodingError
the image only has GrNullCodec loaded so perhaps a dependency issue ? 

MongoTalk was loaded via the advertised coordinates 

In P8 the following subclasses of GrCodec are loaded:

"an OrderedCollection(GRNullCodec GRPharoGenericCodec GRPharoUtf8Codec GRPharoLatin1Codec)"

which explains why in P8 , MongoTalk is working.

Both P8 and P9 where loaded with the same project baselines.
I assume these being codecs that they are loaded by default into the image as part of the regular Pharo distribution ? Are they not being distributed with P9

**Comment by tinchodias** [comment]
It may be fixed in a newer version of Grease. Latest tag is v1.5.1:
https://github.com/SeasideSt/Grease/tree/v1.5.1

Our baseline loads v1.4.6:
https://github.com/pharo-nosql/mongotalk/blob/master/mc/BaselineOfMongoTalk.package/BaselineOfMongoTalk.class/instance/grease..st
